name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-release:
    name: Build and Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: tmuxrs
            asset_name: tmuxrs-linux-amd64
          - os: macOS-latest
            artifact_name: tmuxrs
            asset_name: tmuxrs-macos-amd64
          - os: windows-latest
            artifact_name: tmuxrs.exe
            asset_name: tmuxrs-windows-amd64.exe

    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      
    - name: Install tmux (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get update && sudo apt-get install -y tmux
      
    - name: Install tmux (macOS)
      if: matrix.os == 'macOS-latest'
      run: brew install tmux
      
    - name: Build
      run: cargo build --release
      
    - name: Strip binary (linux and macos)
      if: matrix.os == 'ubuntu-latest' || matrix.os == 'macOS-latest'
      run: strip target/release/${{ matrix.artifact_name }}
      
    - name: Rename binary for release (Unix)
      if: matrix.os != 'windows-latest'
      run: |
        mkdir -p release-assets
        cp target/release/${{ matrix.artifact_name }} release-assets/${{ matrix.asset_name }}
        
    - name: Rename binary for release (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        mkdir release-assets
        copy target\release\${{ matrix.artifact_name }} release-assets\${{ matrix.asset_name }}
      
    - name: Upload binary to release
      uses: softprops/action-gh-release@v1
      with:
        files: release-assets/${{ matrix.asset_name }}
        fail_on_unmatched_files: true

  publish-cargo:
    name: Publish to Cargo
    runs-on: ubuntu-latest
    needs: build-and-release
    if: ${{ success() }}
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      
    - name: Install tmux
      run: sudo apt-get update && sudo apt-get install -y tmux
      
    - name: Dry run first
      run: cargo publish --dry-run --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
      
    - name: Publish to crates.io
      run: cargo publish --token ${{ secrets.CARGO_REGISTRY_TOKEN }}