name: Release

on:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

  build-and-upload:
    name: Build and Upload
    needs: create-release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
        - os: ubuntu-latest
          artifact_name: tmuxrs
          asset_name: tmuxrs-linux-amd64
        - os: macOS-latest
          artifact_name: tmuxrs
          asset_name: tmuxrs-macos-amd64
        - os: windows-latest
          artifact_name: tmuxrs.exe
          asset_name: tmuxrs-windows-amd64.exe

    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      
    - name: Install tmux (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get update && sudo apt-get install -y tmux
      
    - name: Install tmux (macOS)
      if: matrix.os == 'macOS-latest'
      run: brew install tmux
      
    - name: Build
      run: cargo build --release
      
    - name: Strip binary (linux and macos)
      if: matrix.os == 'ubuntu-latest' || matrix.os == 'macOS-latest'
      run: strip target/release/${{ matrix.artifact_name }}
      
    - name: Upload binary to release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.create-release.outputs.upload_url }}
        asset_path: ./target/release/${{ matrix.artifact_name }}
        asset_name: ${{ matrix.asset_name }}
        asset_content_type: application/octet-stream

  publish-cargo:
    name: Publish to Cargo
    runs-on: ubuntu-latest
    needs: build-and-upload
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      
    - name: Install tmux
      run: sudo apt-get update && sudo apt-get install -y tmux
      
    - name: Publish to crates.io
      run: cargo publish --token ${{ secrets.CARGO_REGISTRY_TOKEN }}